[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'none'; script-src 'self' www.google-analytics.com; style-src 'self'; img-src 'self' www.google-analytics.com; frame-ancestors 'none'"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/"
  [headers.values]
    Link = '''
    </start.css>; rel=preload; as=style,
    </favicon.ico>; rel=preload; as=image,
    </img/logo.svg>; rel=preload; as=image,
    </img/ddg_logo.svg>; rel=preload; as=image,
    </js/DynamicBoxes.js>; rel=preload; as=script,
    </js/index.js>; rel=preload; as=script,
    </js/google-analytics.js>; rel=preload; as=script'''

